--- 游戏版本配置
CLIENT_VERSION="1.3.1"

if PLATFORM == "xiaomi" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "uc" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "360" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "youku" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "baidu" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "lenovo" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sj49you" or PLATFORM == "sj49you_tyh" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "downjoy" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "meizu" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "anzhi" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "coolpad" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "huawei" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "xy" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "i4" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "pp" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sogou" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "oppo" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "vivo" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "itools" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "cn91" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "kuaiyong" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "wdj" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "haima" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "baofeng" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "mogoo" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "tongbu" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "am" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "pptv" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "mopo" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "htc" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "gfan" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "mumayi" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "pps" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sy07073" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "tencent" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "iiapple" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "appstore" then
	SERVER_IP = SERVER_APPSTORE
	HOT_UPDATE_IP = SERVER_APPSTORE
	GAME_PARTITION = "game"
	UPDATE_PARTITION = "update"
elseif PLATFORM == "letv" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sj49ios" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sj49ios_fx" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "sj49you_fx" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "jiudu" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "shandou" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "tfgame" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
elseif PLATFORM == "koudai" then
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
else
	--[[
	debug
	]]
	SERVER_IP = SERVER_S1
	HOT_UPDATE_IP = SERVER_S1
	GAME_PARTITION = "game2"
	UPDATE_PARTITION = "update2"
end


CSJ_FILES_UPDATE_VERION = "r1.0.01"--"c2a23802b5376c6e86f72b52442f27d4c0d50af8"
SERVER_LIST_URL_NET = "http://" .. SERVER_IP .. "/" .. GAME_PARTITION;
SERVER_LIST_URL_CN = "http://" .. SERVER_IP .. "/" .. GAME_PARTITION;

